In [1]:
import pandas

In [2]:
extent_file = "base_area_stats/gmw_mjr_v314_national_stats.feather"
chngs_file = "base_area_stats/gmw_v314_annual_chngs_national_stats.feather"

In [3]:
extent_stats_df = pandas.read_feather(extent_file)
chng_stats_df = pandas.read_feather(chngs_file)

In [4]:
chng_stats_df

,index,region,name,2007_count_gain,2008_count_gain,2009_count_gain,2010_count_gain,2015_count_gain,2016_count_gain,2017_count_gain,...,2007_area_loss,2008_area_loss,2009_area_loss,2010_area_loss,2015_area_loss,2016_area_loss,2017_area_loss,2018_area_loss,2019_area_loss,2020_area_loss
0,3,ASM,American Samoa,0,0,0,1,5,0,0,...,0.176841,0.176836,0.235786,0.000000,0.000000,0.000000,0.000000,0.000000,0.176833,0.294732
1,5,AGO,Angola,4010,2224,4404,3487,4250,2321,5115,...,693.111174,324.813834,222.654918,241.049730,323.783728,445.841161,293.407983,464.439262,297.085189,323.581164
2,6,AIA,Anguilla,2,0,7,16,17,2,6,...,1.329983,0.173470,0.231309,0.115654,0.057827,0.231308,0.578250,0.693904,0.578270,0.115654
3,8,ATG,Antigua and Barbuda,155,292,579,939,499,594,497,...,79.244790,18.920970,24.144841,10.792004,24.543440,14.858038,18.628604,27.679768,30.518290,23.793689
4,11,ABW,Aruba,8,0,7,15,36,0,0,...,9.323234,3.563011,1.068905,0.534462,0.712618,0.000000,0.000000,2.850402,0.000000,0.118763
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107,238,VUT,Vanuatu,197,188,406,238,272,94,391,...,3.967017,9.033225,11.782676,18.969138,13.830259,17.321837,12.136615,26.093912,14.416839,79.173582
108,240,VEN,Venezuela,95521,29707,30867,32628,56303,36844,40946,...,7054.475132,3056.239287,1982.509083,2142.069914,3017.614484,2349.475178,1517.591025,1490.315320,1470.504565,2080.390099
109,241,VNM,Vietnam,75140,33236,56786,60827,106427,67410,66284,...,10760.008123,5595.052036,3780.888561,3998.834001,7468.730985,5574.440995,4030.331564,3545.554755,4290.354394,6065.330999
110,242,VIR,"Virgin Islands, U.S.",143,108,184,196,314,149,267,...,20.748195,7.416599,9.443229,8.574025,7.822088,11.874888,12.689251,14.373251,11.531312,13.905864
111,245,YEM,Yemen,1707,547,1029,1104,1317,565,535,...,317.489302,139.142310,54.008137,68.794021,93.561986,71.847091,45.693795,70.636834,41.297932,86.039120

# Remove the columns with the pixel counts so just the area columns are left

In [5]:
cols = extent_stats_df.columns
cols_rm = list()
cols_area = list()
for col in cols:
    if "count" in col:
        cols_rm.append(col)
    elif ("area" in col):
        cols_area.append(col)
print(cols_rm)
print(cols_area)

extent_stats_df = extent_stats_df.drop(columns=cols_rm)


cols = chng_stats_df.columns
cols_rm = list()
cols_area = list()
for col in cols:
    if "count" in col:
        cols_rm.append(col)
    elif ("area" in col):
        cols_area.append(col)
print(cols_rm)
print(cols_area)

chng_stats_df = chng_stats_df.drop(columns=cols_rm)

['1996_count', '2007_count', '2008_count', '2009_count', '2010_count', '2015_count', '2016_count', '2017_count', '2018_count', '2019_count', '2020_count']
['1996_area', '2007_area', '2008_area', '2009_area', '2010_area', '2015_area', '2016_area', '2017_area', '2018_area', '2019_area', '2020_area']
['2007_count_gain', '2008_count_gain', '2009_count_gain', '2010_count_gain', '2015_count_gain', '2016_count_gain', '2017_count_gain', '2018_count_gain', '2019_count_gain', '2020_count_gain', '2007_count_loss', '2008_count_loss', '2009_count_loss', '2010_count_loss', '2015_count_loss', '2016_count_loss', '2017_count_loss', '2018_count_loss', '2019_count_loss', '2020_count_loss']
['2007_area_gain', '2008_area_gain', '2009_area_gain', '2010_area_gain', '2015_area_gain', '2016_area_gain', '2017_area_gain', '2018_area_gain', '2019_area_gain', '2020_area_gain', '2007_area_loss', '2008_area_loss', '2009_area_loss', '2010_area_loss', '2015_area_loss', '2016_area_loss', '2017_area_loss', '2018_area_loss', '2019_area_loss', '2020_area_loss']

In [6]:
chng_stats_df

,index,region,name,2007_area_gain,2008_area_gain,2009_area_gain,2010_area_gain,2015_area_gain,2016_area_gain,2017_area_gain,...,2007_area_loss,2008_area_loss,2009_area_loss,2010_area_loss,2015_area_loss,2016_area_loss,2017_area_loss,2018_area_loss,2019_area_loss,2020_area_loss
0,3,ASM,American Samoa,0.000000,0.000000,0.000000,0.058947,0.294734,0.000000,0.000000,...,0.176841,0.176836,0.235786,0.000000,0.000000,0.000000,0.000000,0.000000,0.176833,0.294732
1,5,AGO,Angola,241.987221,134.236541,264.821634,210.015171,256.244859,140.145784,308.105038,...,693.111174,324.813834,222.654918,241.049730,323.783728,445.841161,293.407983,464.439262,297.085189,323.581164
2,6,AIA,Anguilla,0.115654,0.000000,0.404757,0.925222,0.983064,0.115655,0.346953,...,1.329983,0.173470,0.231309,0.115654,0.057827,0.231308,0.578250,0.693904,0.578270,0.115654
3,8,ATG,Antigua and Barbuda,8.995709,16.949317,33.597409,54.483232,28.957154,34.460739,28.828473,...,79.244790,18.920970,24.144841,10.792004,24.543440,14.858038,18.628604,27.679768,30.518290,23.793689
4,11,ABW,Aruba,0.475057,0.000000,0.415692,0.890770,2.137799,0.000000,0.000000,...,9.323234,3.563011,1.068905,0.534462,0.712618,0.000000,0.000000,2.850402,0.000000,0.118763
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107,238,VUT,Vanuatu,11.498365,10.968181,23.695683,13.886460,15.876910,5.480616,22.818091,...,3.967017,9.033225,11.782676,18.969138,13.830259,17.321837,12.136615,26.093912,14.416839,79.173582
108,240,VEN,Venezuela,5727.888909,1781.094649,1848.734148,1952.983482,3371.421721,2205.908725,2452.112801,...,7054.475132,3056.239287,1982.509083,2142.069914,3017.614484,2349.475178,1517.591025,1490.315320,1470.504565,2080.390099
109,241,VNM,Vietnam,4421.618002,1929.186772,3324.669583,3574.458369,6268.914990,3963.678058,3914.977223,...,10760.008123,5595.052036,3780.888561,3998.834001,7468.730985,5574.440995,4030.331564,3545.554755,4290.354394,6065.330999
110,242,VIR,"Virgin Islands, U.S.",8.281069,6.254394,10.659905,11.358115,18.198001,8.630915,15.473390,...,20.748195,7.416599,9.443229,8.574025,7.822088,11.874888,12.689251,14.373251,11.531312,13.905864
111,245,YEM,Yemen,100.163976,32.032274,60.304171,64.673079,77.188383,33.108299,31.333681,...,317.489302,139.142310,54.008137,68.794021,93.561986,71.847091,45.693795,70.636834,41.297932,86.039120

# Remove the region and name column and sum the columns to get annual totals

In [7]:
extent_totals_df = extent_stats_df.drop(columns=["region", "name"]).sum(axis=0)
extent_totals_df/100 # divide by 100 for km2

1996_area    152604.235030
2007_area    149134.266307
2008_area    147392.574090
2009_area    147139.762667
2010_area    146583.118063
2015_area    145708.048652
2016_area    145347.511182
2017_area    145584.468693
2018_area    145952.647476
2019_area    146010.773297
2020_area    145690.902792
dtype: float64

# Split the gains and losses into seperate dataframes

In [8]:
chng_totals_df = chng_stats_df.drop(columns=["index", "region", "name"]).sum(axis=0)

gain_cols = ["2007_area_gain", "2008_area_gain", "2009_area_gain", "2010_area_gain", "2015_area_gain", "2016_area_gain", "2017_area_gain", "2018_area_gain", "2019_area_gain", "2020_area_gain"]
loss_cols = ["2007_area_loss", "2008_area_loss", "2009_area_loss", "2010_area_loss", "2015_area_loss", "2016_area_loss", "2017_area_loss", "2018_area_loss", "2019_area_loss", "2020_area_loss"]

chng_loss_totals_df = chng_totals_df.drop(gain_cols)
chng_gain_totals_df = chng_totals_df.drop(loss_cols)

chng_loss_stats_df = chng_stats_df.drop(columns=gain_cols)
chng_gain_stats_df = chng_stats_df.drop(columns=loss_cols)

In [9]:
chng_loss_totals_df/100

2007_area_loss    6095.287744
2008_area_loss    2769.751328
2009_area_loss    1745.191624
2010_area_loss    2060.739626
2015_area_loss    3261.626705
2016_area_loss    2140.329153
2017_area_loss    1630.765261
2018_area_loss    1704.844034
2019_area_loss    1978.820490
2020_area_loss    2263.462524
dtype: float64

In [10]:
chng_gain_totals_df/100

2007_area_gain    2625.319021
2008_area_gain    1028.059112
2009_area_gain    1492.380202
2010_area_gain    1504.095021
2015_area_gain    2386.557294
2016_area_gain    1779.791682
2017_area_gain    1867.722773
2018_area_gain    2073.022816
2019_area_gain    2036.946312
2020_area_gain    1943.592018
dtype: float64

# Define the Ommission and Commissions

In [11]:
mng_om = (100-85.63061873343034)/100
mng_com = (100 - 89.28977298408603)/100

In [12]:
print(f"mng_om = {mng_om}")
print(f"mng_com = {mng_com}")

mng_om = 0.1436938126656966
mng_com = 0.10710227015913971

In [13]:
loss_om = (100-73.77949765590216)/100
loss_com = (100-51.42118863049095)/100

In [14]:
print(f"loss_om = {loss_om}")
print(f"loss_com = {loss_com}")

loss_om = 0.2622050234409784
loss_com = 0.48578811369509045

In [15]:
gain_om = (100-69.97109826589596)/100
gain_com = (100-50.0)/100

In [16]:
print(f"gain_om = {gain_om}")
print(f"gain_com = {gain_com}")

gain_om = 0.3002890173410404
gain_com = 0.5

# Apply to annual totals to see what the numbers are:

In [17]:
extent_totals_corr_df = extent_totals_df + (extent_totals_df * mng_om) - (extent_totals_df * mng_com)
extent_totals_corr_df/100

1996_area    158188.259382
2007_area    154591.319151
2008_area    152785.895730
2009_area    152523.833547
2010_area    151946.820458
2015_area    151039.730908
2016_area    150666.000815
2017_area    150911.628968
2018_area    151293.279980
2019_area    151353.532715
2020_area    151021.957654
dtype: float64

In [18]:
chng_loss_totals_corr_df = chng_loss_totals_df + (chng_loss_totals_df * loss_om) - (chng_loss_totals_df * loss_com)
chng_loss_totals_corr_df/100

2007_area_loss    4732.484474
2008_area_loss    2150.481767
2009_area_loss    1354.996288
2010_area_loss    1599.993092
2015_area_loss    2532.382127
2016_area_loss    1661.787747
2017_area_loss    1266.153725
2018_area_loss    1323.669736
2019_area_loss    1536.389690
2020_area_loss    1757.390578
dtype: float64

In [19]:
chng_gain_totals_corr_df = chng_gain_totals_df  + (chng_gain_totals_df * gain_om) - (chng_gain_totals_df * gain_com)
chng_gain_totals_corr_df/100

2007_area_gain    2101.013980
2008_area_gain     822.744416
2009_area_gain    1194.335485
2010_area_gain    1203.710727
2015_area_gain    1909.935592
2016_area_gain    1424.347736
2017_area_gain    1494.718022
2018_area_gain    1659.017393
2019_area_gain    1630.145762
2020_area_gain    1555.435346
dtype: float64

# Calculate the net change from the corrected gains and losses

In [20]:
net_chng_vals = dict()

gmw_chng_years = [2007, 2008, 2009, 2010, 2015, 2016, 2017, 2018, 2019, 2020]
for chng_year in gmw_chng_years:
    net_chng_vals[f"{chng_year}_net_chng"] = chng_loss_totals_corr_df[f"{chng_year}_area_loss"] - chng_gain_totals_corr_df[f"{chng_year}_area_gain"]

net_chng_corr_sr = pandas.Series(net_chng_vals)
net_chng_corr_sr/100

2007_net_chng    2631.470495
2008_net_chng    1327.737351
2009_net_chng     160.660803
2010_net_chng     396.282365
2015_net_chng     622.446535
2016_net_chng     237.440010
2017_net_chng    -228.564298
2018_net_chng    -335.347656
2019_net_chng     -93.756072
2020_net_chng     201.955232
dtype: float64

# Calculate the Country Extent Corrections

In [21]:
# Make a copy of the extent dataframe
extent_stats_corr_df = extent_stats_df.copy()
# Apply correction to the 1996 layer - Uncomment line below to add this correction to analysis
#extent_stats_corr_df["1996_area"] = extent_stats_df["1996_area"] + (extent_stats_df["1996_area"] * mng_om) - (extent_stats_df["1996_area"] * mng_com)

In [22]:
# Print the global totals - check whether 1996 values look correct
extent_stats_corr_df.drop(columns=["region", "name"]).sum(axis=0)/100

1996_area    152604.235030
2007_area    149134.266307
2008_area    147392.574090
2009_area    147139.762667
2010_area    146583.118063
2015_area    145708.048652
2016_area    145347.511182
2017_area    145584.468693
2018_area    145952.647476
2019_area    146010.773297
2020_area    145690.902792
dtype: float64

# Calculate the Per-country corrected gains and losses

In [23]:
chng_gain_corr_stats_df = chng_gain_stats_df.copy()
chng_gain_corr_stats_df[gain_cols] = chng_gain_corr_stats_df[gain_cols] + (chng_gain_corr_stats_df[gain_cols] * gain_om) - (chng_gain_corr_stats_df[gain_cols] * gain_com)
chng_gain_corr_stats_df

,index,region,name,2007_area_gain,2008_area_gain,2009_area_gain,2010_area_gain,2015_area_gain,2016_area_gain,2017_area_gain,2018_area_gain,2019_area_gain,2020_area_gain
0,3,ASM,American Samoa,0.000000,0.000000,0.000000,0.047175,0.235873,0.000000,0.000000,0.000000,0.000000,0.000000
1,5,AGO,Angola,193.659715,107.428030,211.933845,168.072835,205.069947,112.157131,246.573078,156.453035,320.775151,174.332810
2,6,AIA,Anguilla,0.092557,0.000000,0.323922,0.740445,0.786736,0.092557,0.277663,0.000000,0.185097,0.185115
3,8,ATG,Antigua and Barbuda,7.199167,13.564352,26.887637,43.602333,23.174093,27.578551,23.071110,29.112153,21.262732,10.492191
4,11,ABW,Aruba,0.380183,0.000000,0.332674,0.712873,1.710857,0.000000,0.000000,0.095044,0.000000,1.900950
...,...,...,...,...,...,...,...,...,...,...,...,...,...
107,238,VUT,Vanuatu,9.202015,8.777715,18.963395,11.113181,12.706117,4.386076,18.261068,20.796734,9.098903,10.646351
108,240,VEN,Venezuela,4583.966587,1425.390486,1479.521635,1562.951232,2698.111776,1765.364526,1962.398944,1981.762659,1618.546953,1365.469221
109,241,VNM,Vietnam,3538.572326,1543.906986,2660.696554,2860.599776,5016.943817,3172.088018,3133.113275,3802.754808,3705.220840,4837.495275
110,242,VIR,"Virgin Islands, U.S.",6.627249,5.005323,8.531005,9.089775,14.563661,6.907226,12.383184,10.480816,9.925216,7.190912
111,245,YEM,Yemen,80.160130,25.635077,48.260766,51.757155,61.773015,26.496208,25.076001,37.449585,45.194026,27.135169

In [24]:
chng_loss_corr_stats_df = chng_loss_stats_df.copy()
chng_loss_corr_stats_df[loss_cols] = chng_loss_corr_stats_df[loss_cols] + (chng_loss_corr_stats_df[loss_cols] * loss_om) - (chng_loss_corr_stats_df[loss_cols] * loss_com)
chng_loss_corr_stats_df

,index,region,name,2007_area_loss,2008_area_loss,2009_area_loss,2010_area_loss,2015_area_loss,2016_area_loss,2017_area_loss,2018_area_loss,2019_area_loss,2020_area_loss
0,3,ASM,American Samoa,0.137302,0.137298,0.183069,0.000000,0.000000,0.000000,0.000000,0.000000,0.137296,0.228835
1,5,AGO,Angola,538.143236,252.190953,172.873043,187.155086,251.391162,346.158616,227.806919,360.598497,230.661965,251.233887
2,6,AIA,Anguilla,1.032621,0.134685,0.179593,0.089796,0.044898,0.179592,0.448963,0.538759,0.448979,0.089796
3,8,ATG,Antigua and Barbuda,61.526995,14.690561,18.746463,8.379095,19.055942,11.536032,14.463563,21.491040,23.694917,18.473822
4,11,ABW,Aruba,7.238716,2.766382,0.829916,0.414965,0.553289,0.000000,0.000000,2.213100,0.000000,0.092209
...,...,...,...,...,...,...,...,...,...,...,...,...,...
107,238,VUT,Vanuatu,3.080059,7.013549,9.148269,14.727959,10.738047,13.448968,9.423073,20.259755,11.193477,61.471708
108,240,VEN,Venezuela,5477.213781,2372.915863,1539.253576,1663.139303,2342.926913,1824.172257,1178.283334,1157.106016,1141.724610,1615.250052
109,241,VNM,Vietnam,8354.252256,4344.093012,2935.545812,3104.762338,5798.849031,4328.090251,3129.217578,2752.828666,3331.103700,4709.225551
110,242,VIR,"Virgin Islands, U.S.",16.109250,5.758373,7.331883,6.657018,6.073202,9.219864,9.852149,11.159635,8.953106,10.796748
111,245,YEM,Yemen,246.504062,108.032443,41.932831,53.412841,72.643108,55.783297,35.477435,54.843633,32.064413,66.802228

# Save the gains and losses to an Excel Sheet

In [25]:
chng_gain_corr_stats_df.to_excel("gmw_v314_chng_gain_obs2obs_corrected_testnb.xlsx")
chng_loss_corr_stats_df.to_excel("gmw_v314_chng_loss_obs2obs_corrected_testnb.xlsx")

# Print the global summaries to check they look correct

In [26]:
chng_gain_corr_totals = chng_gain_corr_stats_df.drop(columns=["index", "region", "name"]).sum(axis=0)
chng_gain_corr_totals/100

2007_area_gain    2101.013980
2008_area_gain     822.744416
2009_area_gain    1194.335485
2010_area_gain    1203.710727
2015_area_gain    1909.935592
2016_area_gain    1424.347736
2017_area_gain    1494.718022
2018_area_gain    1659.017393
2019_area_gain    1630.145762
2020_area_gain    1555.435346
dtype: float64

In [27]:
chng_loss_corr_totals = chng_loss_corr_stats_df.drop(columns=["index", "region", "name"]).sum(axis=0)
chng_loss_corr_totals/100

2007_area_loss    4732.484474
2008_area_loss    2150.481767
2009_area_loss    1354.996288
2010_area_loss    1599.993092
2015_area_loss    2532.382127
2016_area_loss    1661.787747
2017_area_loss    1266.153725
2018_area_loss    1323.669736
2019_area_loss    1536.389690
2020_area_loss    1757.390578
dtype: float64

# Create copies of the dataframes and set the region to be the index so the countries get correctly matched

In [28]:
extent_stats_corr_test_df = extent_stats_corr_df.copy()
extent_stats_corr_test_df = extent_stats_corr_test_df.set_index("region")

chng_gain_corr_stats_test_df = chng_gain_corr_stats_df.copy()
chng_gain_corr_stats_test_df = chng_gain_corr_stats_test_df.set_index("region")
chng_loss_corr_stats_test_df = chng_loss_corr_stats_df.copy()
chng_loss_corr_stats_test_df = chng_loss_corr_stats_test_df.set_index("region")

# Apply change correction to calculate country extent per year

In [29]:
gmw_base_years = [1996, 2007, 2008, 2009, 2010, 2015, 2016, 2017, 2018, 2019]
gmw_chng_years = [2007, 2008, 2009, 2010, 2015, 2016, 2017, 2018, 2019, 2020]

for base_year, chng_year in zip(gmw_base_years, gmw_chng_years): 
    extent_stats_corr_test_df[f"{chng_year}_area"] = extent_stats_corr_test_df[f"{base_year}_area"] - chng_loss_corr_stats_test_df[f"{chng_year}_area_loss"] + chng_gain_corr_stats_test_df[f"{chng_year}_area_gain"]

# Find countries for which the area is NaN as we have no changes for these countries

In [30]:
no_chng_rgns_df = extent_stats_corr_test_df[extent_stats_corr_test_df.isna().any(axis=1)]
no_chng_rgns_df

,name,1996_area,2007_area,2008_area,2009_area,2010_area,2015_area,2016_area,2017_area,2018_area,2019_area,2020_area
region,,,,,,,,,,,,
BMU,Bermuda,20.941199,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
COK,Cook Islands,3.271538,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ATF,French Southern Territories,672.301758,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
KIR,Kiribati,146.482619,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MDV,Maldives,97.344067,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MHL,Marshall Islands,32.544645,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SXM,Sint Maarten,5.382281,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
STP,São Tomé and Príncipe,48.385207,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TUV,Tuvalu,8.911715,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
WLF,Wallis and Futuna,29.362414,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Replace the NaN values will the 1996 area

In [31]:
for i, row in no_chng_rgns_df.iterrows():
    print(i)
    for chng_year in gmw_chng_years: 
        #print(f"\t{chng_year}")
        extent_stats_corr_test_df.at[i, f"{chng_year}_area"] = extent_stats_corr_test_df.loc[[i]]["1996_area"]

BMU
COK
ATF
KIR
MDV
MHL
SXM
STP
TUV
WLF

In [32]:
extent_stats_corr_test_df

,name,1996_area,2007_area,2008_area,2009_area,2010_area,2015_area,2016_area,2017_area,2018_area,2019_area,2020_area
region,,,,,,,,,,,,
ASM,American Samoa,32.599267,32.461965,32.324667,32.141598,32.188772,32.424645,32.424645,32.424645,32.424645,32.287349,32.058514
AGO,Angola,29325.123955,28980.640435,28835.877511,28874.938313,28855.856063,28809.534848,28575.533363,28594.299522,28390.154060,28480.267246,28403.366169
AIA,Anguilla,4.278923,3.338858,3.204173,3.348503,3.999152,4.740990,4.653955,4.482655,3.943896,3.680014,3.775332
ATG,Antigua and Barbuda,859.980296,805.652469,804.526259,812.667434,847.890672,852.008822,868.051341,876.658888,884.280001,881.847817,873.866186
ABW,Aruba,55.052209,48.193675,45.427293,44.930051,45.227959,46.385528,46.385528,46.385528,44.267472,44.267472,46.076212
...,...,...,...,...,...,...,...,...,...,...,...,...
VEN,Venezuela,284856.099918,283962.852723,283015.327346,282955.595405,282855.407333,283210.592197,283151.784466,283935.900076,284760.556719,285237.379061,284987.598231
VNM,Vietnam,196419.491282,191603.811353,188803.625327,188528.776068,188284.613507,187502.708293,186346.706060,186350.601757,187400.527899,187774.645039,187902.914763
VIR,"Virgin Islands, U.S.",264.879646,255.397645,254.644594,255.843717,258.276474,266.766933,264.454295,266.985330,266.306511,267.278621,263.672785
WLF,Wallis and Futuna,29.362414,29.362414,29.362414,29.362414,29.362414,29.362414,29.362414,29.362414,29.362414,29.362414,29.362414
YEM,Yemen,1899.156310,1732.812377,1650.415011,1656.742946,1655.087260,1644.217167,1614.930079,1604.528644,1587.134596,1600.264210,1560.597150

# Export country extents to Excel sheet.

In [33]:
extent_stats_corr_test_df.to_excel("gmw_v314_country_areas_corrected_obs2obs_testnb.xlsx")